controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
get_users_by_email:
    path: '/api/users/by-email/{email}'
    controller: 'App\Controller\UserController::getUsersByEmail'
    methods: ['GET']
# api_login_check:
#     path: /api/login_check
#     methods: ['POST']